---
- hosts: localhost
  gather_facts: true
  become: true
  vars:
    workadventure_domain: "nerdadventure.de"
    workadventure_start_room: "/_/global/copykatze.github.io/wa-nerdadventure/maps/silpion_2og.json"
    jitsi_url: "jitsi.1533.eu"
    jitsi_private_mode: False
    skip_full_upgrade: True
    ansible_become_pass: "{{ local_become_pass }}"
  tasks:

    - include_role:
        name: user_setup
      loop:
        - "{{ users.admin }}"

    - include_role:
        name: generic_setup
      tags:
        - packages

    - include_role:
        name: security
      tags:
        - security

    - include_role:
        name: docker_setup
      tags:
        - packages

    - include_role:
        name: workadventure_setup
      tags:
        - product
